### ISSUE TITLE
running predict in python file for streamlit

### ISSUE THREAD

**Issue by AyalaEl** [advimman/lama#116]
I'm trying to run predict.py in a streamlit app, but it doesn't save the new image

the image is saved like this:
uploaded_file = st.file_uploader(label, type=['jpg'])
image = np.array(Image.open(uploaded_file))
cv2.imwrite(f"/content/lama/data_for_prediction/curr_image.jpg", image)

the masked saved like this:
bimask= boolean mask
plt.imsave(f"/content/lama/data_for_prediction/curr_image_mask.png", bimask, cmap='gray')

and tried to run predict, with a lot of variations of this:
os.system('python /content/lama/bin/predict.py model.path=/content/lama/big-lama indir=/content/lama/data_for_prediction outdir=/content/output dataset.img_suffix=.jpg > /dev/null')

I don't get an error from os.system, curr_image and curr_image_mask exist where they should how they should, but nothing is saved into  '/content/output'.

**Comment by windj007** [comment]
Hi! The issue is probably caused by the environment. Just a couple of days ago I tested the code in colab and it worked (and nothing changed since then).

If you run `python /content/lama/bin/predict.py model.path=/content/lama/big-lama indir=/content/lama/data_for_prediction outdir=/content/output dataset.img_suffix=.jpg` without `os.system`, does it work as intended in your environment? If you remove `> /dev/null`, what does it output?

You'd probably better refer to an [existing third-party streamlit app](https://github.com/saic-mdal/lama/issues/94) or [colab](https://colab.research.google.com/github/saic-mdal/lama/blob/master/colab/LaMa_inpainting.ipynb). Also, if you're using LaMa from a python app, calling it via `os.system` might be suboptimal.
