### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/content/output/1_mask.png'

### ISSUE THREAD

**Issue by jadewu9** [advimman/lama#245]
这个文件夹是在哪创建的，找了一通也没找见相关代码把这个文件夹创建出来

**Comment by jadewu9** [comment]
就是这个colab的实例，想着看一看来的

**Comment by jadewu9** [comment]
也找不到这个保存修复后图像的代码

**Comment by Xinshuai-Lyu** [comment]
[Copy_of_LaMa_inpainting.ipynb.zip](https://github.com/advimman/lama/files/12234678/Copy_of_LaMa_inpainting.ipynb.zip)
1. Download my colab
2. edit /content/lama/saicinpainting/training/modules/fake_fakes.py, you need to change **from kornia import SamplePadding** to
**from kornia.constants import SamplePadding**
3. edit /content/lama/bin/predict.py, you need to change **device = torch.device(predict_config.device)** (line 43) to **device = torch.device("cpu")**
![WX20230802-004026](https://github.com/advimman/lama/assets/79286397/1641fef0-f8b7-4e9d-9ed6-0cb5f852fbfc)

**Comment by nikprt** [comment]
@Xinshuai-Lyu I followed your changes but in the step of inpainting, I am still getting the error:
`FileNotFoundError: [Errno 2] No such file or directory: '/content/output/1224276_original_mask.png'`

Looking into the **predict.log** file in the **outputs** folder shows this:

`[2023-11-02 11:30:50,933][saicinpainting.utils][WARNING] - Setting signal 10 handler <function print_traceback_handler at 0x7eda504a9ea0>
[2023-11-02 11:30:50,933][__main__][CRITICAL] - Prediction failed due to [Errno 2] No such file or directory: '/content/lama/big-lama/config.yaml':
Traceback (most recent call last):
  File "/content/lama/bin/predict.py", line 46, in main
    with open(train_config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/lama/big-lama/config.yaml'`

It seems that somehow, the folder /big-lama/ is not created and therefore I cannot fand any "config.yaml". Would appreciate some help here if anyone knows how to fix this!

**Comment by Xinshuai-Lyu** [comment]
@nikprt 

!curl -L $(yadisk-direct https://disk.yandex.ru/d/ouP6l8VJ0HpMZg) -o big-lama.zip 

The above link is broken, find this and replace it with:

!curl -LJO https://huggingface.co/smartywu/big-lama/resolve/main/big-lama.zip

**Comment by nikprt** [comment]
@Xinshuai-Lyu thanks for your help! Do I just have to replace the model download you mentioned in the original colab or do I have to additionally make those 3 changes you mentioned before?

**Comment by Xinshuai-Lyu** [comment]
@nikprt 

Follow my previous guide and

!curl -L $(yadisk-direct https://disk.yandex.ru/d/ouP6l8VJ0HpMZg) -o big-lama.zip

The above link is broken, find this and replace it with:

!curl -LJO https://huggingface.co/smartywu/big-lama/resolve/main/big-lama.zip

Have tested it this morning and it works. 

Hope it can help you. Enjoy :)

**Comment by senya-ashukha** [comment]
That is amazing! TY @Xinshuai-Lyu
